version: "3.8"

services:
  node-service:
    build: ./node-service
    ports:
      - "5000:5000"  # Expose Node.js to the outside world
    depends_on:
      - python-service
      - mongodb
    networks:
      - backend

  python-service:
    build: ./python-service
    expose:
      - "6000"  # No public access, only internal
    networks:
      - backend

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    expose:
      - "27017"  # No public access, only internal
    networks:
      - backend

networks:
  backend:
    driver: bridge
